# Generated by Django 3.2.13 on 2023-04-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='id de Producto')),
                ('nombre_prod', models.CharField(max_length=40, verbose_name='Nombre_prod')),
                ('imagen_prod', models.ImageField(blank=True, null=True, upload_to='Productos')),
                ('descripcion_prod', models.TextField(verbose_name='Descripcion')),
                ('cantidad_prod', models.IntegerField(verbose_name='Cantidad de productos')),
                ('precio_prod', models.IntegerField(verbose_name='Precio')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
