# Generated by Django 4.2.1 on 2023-05-24 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetVenta', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Detalle Venta')),
                ('cantidad_prod_venta', models.IntegerField(verbose_name='Cantidad de productos')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Venta')),
                ('fech_venta', models.DateField(verbose_name='FechaVenta')),
                ('descuento', models.IntegerField(verbose_name='Descuento Venta')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('iva', models.IntegerField(verbose_name='Iva')),
                ('total', models.IntegerField(verbose_name='Total')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='marca_prod',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo_prod',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_prod',
            field=models.ImageField(blank=True, null=True, upload_to='Productos', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_prod',
            field=models.CharField(max_length=40, verbose_name='Nombre de producto'),
        ),
        migrations.CreateModel(
            name='subcategoria',
            fields=[
                ('idSubCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de SubCategoria')),
                ('nombreSubCategoria', models.CharField(max_length=50, verbose_name='Nombre de la SubCategoria')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subcategoria'),
        ),
    ]
