# Generated by Django 4.2.1 on 2023-05-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detalleventa_venta_producto_marca_prod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_vencimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
